repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0
      hooks:
          - id: check-added-large-files
            exclude: src/convert_labse_tf_pt/data/smaller_vocab/vocab-en-fr-es-de-zh-ar-zh_classical-it-ja-ko-nl-pl-pt-th-tr-ru.txt
          - id: check-ast
          - id: check-merge-conflict
          - id: check-toml
          - id: check-yaml
          - id: end-of-file-fixer
          - id: requirements-txt-fixer
          - id: trailing-whitespace
    - repo: https://github.com/charliermarsh/ruff-pre-commit
      rev: "v0.9.2"
      hooks:
          - id: ruff
          - id: ruff-format
    # Disabling until https://github.com/PyCQA/docformatter/pull/287 is released.
    # - repo: https://github.com/myint/docformatter/
    #   rev: v1.7.5
    #   hooks:
    #       - id: docformatter
    #         args:
    #             [
    #                 "--in-place",
    #                 "--wrap-summaries=88",
    #                 "--wrap-descriptions=88",
    #                 "--pre-summary-newline",
    #             ]
